<?
/**
 * emuControlCenter language system file
 * ------------------------------------------
 * language:	jp (japanese)
 * author:	Yoshi Matsu
 * date:	2006/09/09 
 * ------------------------------------------
 */
$i18n['global'] = array(
	// -------------------------------------------------------------
	// context menu navigation
	// -------------------------------------------------------------
	'restart_title' =>
		"eCCの再起動",
	'restart_msg' =>
		"再起動をして変更を確認して下さい！",
	'error_title' =>
		"エラー",
	'error_text' =>
		"エラーが起きました！",
	'done_title' =>
		"実行されました",
	'done_msg' =>
		"終了しました！",

	/* 0.9.2 WIP 17 */
	'dialog_button_help' =>
		"ヘルプ",
	'dialog_button_apply' =>
		"適用",
	'dialog_button_no' =>
		"いいえ",
	'dialog_button_yes' =>
		"はい",
	'dialog_button_close' =>
		"閉じる",
	'dialog_button_cancel' =>
		"キャンセル",
	'dialog_button_ok' =>
		"OK",
	'dialog_button_accept' =>
		"承諾",
	'dialog_button_reject' =>
		"未承諾",
	'dialog_button_all' =>
		"全て",
	'dialog_button_none' =>
		"ありません",

	/* 0.9.2 WIP 19 */
	'dialog_dont_show_again' =>
		"Donｴt show this dialog again",

	/* 0.9.6 WIP 13 */
	'start' =>
		"Start",
	'emulator' =>
		"Emulator",
	'name' =>
		"Name",
	'fileName' =>
		"Filename",
	'fileNameShort' =>
		"File",
	'filePath' =>
		"Directory",
	'filePathShort' =>
		"Dir",
	'crc32' =>
		"CRC32",
	'platform' =>
		"Platform",
	'size' =>
		"Size",
	'packed' =>
		"Packed",
	'category' =>
		"Category",

	'closeWindow' =>
		"Close",

	'noInformationsAvailable' =>
		"No informations available",
	'generatedBy' =>
		"generated by",
	'invalidDataEncodingError' =>
		"invalid data encoding error...",

	'dataSaved' =>
		"Data saved",
	'dataRemoved' =>
		"The data has been removed!",
	'dataUpdated' =>
		"The data has been updated!",
	'dataAdded' =>
		"The data has been added!",

	'fileInfos' =>
		"File informations",
	'metaInfos' =>
		"Meta informations",

	'save' =>
		"Save",
	'saveAndClose' =>
		"Save and close",
	'close' =>
		"Close",
	'cancel' =>
		"Cancel",

	/* 0.9.6 WIP 15 */
	'first' =>
		"First",
	'last' =>
		"Last",
	'next' =>
		"Next",
	'prev' =>
		"Previous",
	'prevShort' =>
		"Prev",

	'image' =>
		"Image",
	'all' =>
		"all",
	'allFound' =>
		"All found",
	'preview' =>
		"Preview",
	'searchField' =>
		"Search in field",
	'searchOperator' =>
		"Search operator",
	'searchRatings' =>
		"Search for rating",
	
	'change' =>
		"Change",
	'options' =>
		"Options",

	'emuNotFound' =>
		"Emu not found",

	'statistics' =>
		"Statistics",
	'parsed' =>
		"Parsed",
	'added' =>
		"Added",
	'invalid' =>
		"Invalid",
	'unchanged' =>
		"Unchanged",

	'title' =>
		"Title",


	'rename' =>
		"Rename",
	'copy' =>
		"Copy",
	'remove' =>
		"Remove",

	'selectFolder' =>
		"Select folder",

	/* 0.9.6 WIP 16 */
	'rateRom' =>
		"Rate the rom",

);
?>