<?
/**
 * emuControlCenter language system file
 * ------------------------------------------
 * language:	en (english)
 * author:	andreas scheibel
 * date:	2006/09/09 
 * ------------------------------------------
 */
$i18n['global'] = array(
	// -------------------------------------------------------------
	// context menu navigation
	// -------------------------------------------------------------
	'restart_title' =>
		"Restart ecc",
	'restart_msg' =>
		"please restart ecc to see the changes!",
	'error_title' =>
		"Error",
	'error_text' =>
		"Error found!",
	'done_title' =>
		"Action done",
	'done_msg' =>
		"This is done!",

	/* 0.9.2 WIP 17 */
	'dialog_button_help' =>
		"Help",
	'dialog_button_apply' =>
		"Apply",
	'dialog_button_no' =>
		"No",
	'dialog_button_yes' =>
		"Yes",
	'dialog_button_close' =>
		"close",
	'dialog_button_cancel' =>
		"Cancel",
	'dialog_button_ok' =>
		"OK",
	'dialog_button_accept' =>
		"Accept",
	'dialog_button_reject' =>
		"Reject",
	'dialog_button_all' =>
		"All",
	'dialog_button_none' =>
		"None",

	/* 0.9.2 WIP 19 */
	'dialog_dont_show_again' =>
		"Don´t show this dialog again",

	/* 0.9.6 WIP 13 */
	'start' =>
		"Start",
	'emulator' =>
		"Emulator",
	'name' =>
		"Name",
	'fileName' =>
		"Filename",
	'fileNameShort' =>
		"File",
	'filePath' =>
		"Directory",
	'filePathShort' =>
		"Dir",
	'crc32' =>
		"CRC32",
	'platform' =>
		"Platform",
	'size' =>
		"Size",
	'packed' =>
		"Packed",
	'category' =>
		"Category",

	'closeWindow' =>
		"Close",

	'noInformationsAvailable' =>
		"No informations available",
	'generatedBy' =>
		"generated by",
	'invalidDataEncodingError' =>
		"invalid data encoding error...",

	'dataSaved' =>
		"Data saved",
	'dataRemoved' =>
		"The data has been removed!",
	'dataUpdated' =>
		"The data has been updated!",
	'dataAdded' =>
		"The data has been added!",

	'fileInfos' =>
		"File informations",
	'metaInfos' =>
		"Meta informations",

	'save' =>
		"Save",
	'saveAndClose' =>
		"Save and close",
	'close' =>
		"Close",
	'cancel' =>
		"Cancel",

	/* 0.9.6 WIP 15 */
	'first' =>
		"First",
	'last' =>
		"Last",
	'next' =>
		"Next",
	'prev' =>
		"Previous",
	'prevShort' =>
		"Prev",

	'image' =>
		"Image",
	'all' =>
		"all",
	'allFound' =>
		"All found",
	'preview' =>
		"Preview",
	'searchField' =>
		"Search in field",
	'searchOperator' =>
		"Search operator",
	'searchRatings' =>
		"Search for rating",
	
	'change' =>
		"Change",
	'options' =>
		"Options",

	'emuNotFound' =>
		"Emu not found",

	'statistics' =>
		"Statistics",
	'parsed' =>
		"Parsed",
	'added' =>
		"Added",
	'invalid' =>
		"Invalid",
	'unchanged' =>
		"Unchanged",

	'title' =>
		"Title",


	'rename' =>
		"Rename",
	'copy' =>
		"Copy",
	'remove' =>
		"Remove",

	'selectFolder' =>
		"Select folder",

	/* 0.9.6 WIP 16 */
	'rateRom' =>
		"Rate the rom",
		
	/* 0.9.7 WIP 01 */
	'total' =>
		"total",
	'startRom' =>
		"Start rom",
	'zip' =>
		"Zip",
	'fileInfo' =>
		"File info",
	'edit' =>
		"Edit",
	'hiscore' =>
		"Hiscore",
		
	/* 0.9.7 WIP 02 */
	'of' =>
		"of",
		
	/* 0.9.7 WIP 04 */
	'informations' =>
		"Informations",
	'contact'=>
		"Contact",
	'author'=>
		"Author",
	'date'=>
		"Date",
	'description'=>
		"Description",
	'website'=>
		"Website",
		
	/* 0.9.7 WIP 07 */
	'reset'=>
		"Reset",

	/* 0.9.8 WIP 02 */
	'yes'=>
		"Yes",
	'no'=>
		"No",
	'count'=>
		"Count",
	'time'=>
		"Time",
);
?>